name: build and deploy mkdocs to github pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive" 
          fetch-depth: 0       # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip     # install pip
          python -m pip install mkdocs            # install mkdocs 
          python -m pip install mkdocs-material   # install material theme
          python -m pip install mkdocstrings      # install material theme
          python -m pip install mkdocstrings-python    # install material theme
      - name: Build site
        run: mkdocs build
      - name: Deploy
        run: mkdocs gh-deploy --force